FROM DOCKER_USER_NAME/DOCKER_TARGET_ARCH_buildroot_sdk:base


# install RK1126 dependencies
RUN rk1126Deps='repo git gitk git-gui gcc-arm-linux-gnueabihf u-boot-tools device-tree-compiler gcc-aarch64-linux-gnu mtools parted python-linaro-image-tools linaro-image-tools autoconf autotools-dev libsigsegv2 m4 intltool libdrm-dev binutils build-essential patch gzip gawk bzip2 perl tar cpio python unzip rsync file bc libqt4-dev libglib2.0-dev libgtk2.0-dev libglade2-dev cvs rsync openssh-client subversion asciidoc w3m dblatex graphviz python-matplotlib libdb1-compat tzdata libssl-dev expect fakeroot cmake flex bison keychain lib32gcc-7-dev  g++-7  libstdc++-7-dev' \
    && apt-get -y install ${rk1126Deps} \
    && apt -y autoremove

