version: '3.0'
services:
  nfs:
    image: rayruan/nfs-server_x86_64
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    ports:
      - 2049:2049
    volumes:
      - /mnt/cd1/github/falcon/dkhub/nfs_server/configs/exports:/etc/exports:ro
      - /lib/modules:/lib/modules:ro
      - /mnt/cd1/nfsRoot:/mnt/cd1/nfsRoot
      - /mnt/cd1/nfsTmp1:/mnt/cd1/nfsTmp1
      - /mnt/cd1/nfsTmp2:/mnt/cd1/nfsTmp2
    entrypoint:
      - /usr/local/bin/entrypoint.sh
    restart: always

